spring:
  data:
    mongodb:
      uri: mongodb+srv://se-candidate:h3bEDbXbDX8rto5x4yN3d6C@pyx-interview-cluster0.2zo55.mongodb.net/interview?ssl=true&retryWrites=true&w=majority&authMechanism=SCRAM-SHA-1
